### ISSUE TITLE
java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by zjpjack** [twitter/cassovary#191]
Hi,

I am trying to build cassovary on mac(version 10.10.4), when I use ./sbt test, there is error as following.
Does anyone know how to figure this?
Thanks

The log file for this session is at /var/folders/fl/xbhv8lfx32dff1pbd0dmx4xw0000gn/T/sbt7317476583123018292.log
java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sbt.State$.handleException(State.scala:242)
	at sbt.State$$anon$1.handleError(State.scala:205)
	at sbt.MainLoop$.handleException(MainLoop.scala:105)
	at sbt.MainLoop$.next(MainLoop.scala:101)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
Error during sbt execution: java.lang.OutOfMemoryError: PermGen space

**Comment by pankajgupta** [comment]
Interesting -- you can try adding "-XX:PermSize=256m" as an additional
option in ./sbt file, but the problem could be something else too...

What is your java version?
As mentioned in README, "Also, Cassovary requires Java 7+ and the last
Cassovary version to support Java 6 was 3.4.0."

**Comment by tlasica** [comment]
I sometimes got the OutOfMemory error after running test several times in one sbt session. It may give you a hint.

**Comment by zjpjack** [comment]
This problems is solved through adding additional permsize parameter. Thanks.

**Comment by pankajgupta** [comment]
How about a pull request to bring it into master?

**Comment by tlasica** [comment]
finishing it

**Comment by pankajgupta** [comment]
Fixed in master
