### ISSUE TITLE
PerformanceBenchmark doesn't seem to be able to read gzipped files

### ISSUE THREAD

**Issue by lintool** [twitter/cassovary#222]
The class `com.twitter.cassovary.PerformanceBenchmark` doesn't seem to be able to read gzipped files. Example:

```
[jimmylin@tibanna cassovary]$ ls cassovary-benchmarks/src/main/resources/graphs/soc-LiveJournal1.txt.gz 
cassovary-benchmarks/src/main/resources/graphs/soc-LiveJournal1.txt.gz
[jimmylin@tibanna cassovary]$ ./sbt "project cassovary-benchmarks" "run-main com.twitter.cassovary.PerformanceBenchmark -local=soc-LiveJournal1 -separator=9 -globalpr"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[info] Loading project definition from /scratch0/jimmylin/cassovary/project
[info] Set current project to cassovary (in build file:/scratch0/jimmylin/cassovary/)
[info] Set current project to cassovary-benchmarks (in build file:/scratch0/jimmylin/cassovary/)
[info] Running com.twitter.cassovary.PerformanceBenchmark -local=soc-LiveJournal1 -separator=9 -globalpr
Reading soc-LiveJournal1 graph from src/main/resources/graphs
Using Character (9 in Int) as separator
Oct 08, 2016 11:04:03 PM com.twitter.cassovary.util.io.FileReader <init>
INFO: Starting reading from file src/main/resources/graphs/soc-LiveJournal1.txt.gz...

Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
    at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.readLine(BufferedReader.java:324)
    at java.io.BufferedReader.readLine(BufferedReader.java:389)
    at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
    at com.twitter.cassovary.util.io.FileReader.checkNext(FileReader.scala:40)
    at com.twitter.cassovary.util.io.FileReader.<init>(FileReader.scala:18)
    at com.twitter.cassovary.util.io.TwoTsFileReader.<init>(FileReader.scala:65)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader.twoNodeIdsIterator(ListOfEdgesGraphReader.scala:78)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader$$anon$1$$anon$3.<init>(ListOfEdgesGraphReader.scala:101)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader$$anon$1.iterator(ListOfEdgesGraphReader.scala:88)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader$$anon$5.idAndEdgesIterator$lzycompute(ListOfEdgesGraphReader.scala:169)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader$$anon$5.idAndEdgesIterator(ListOfEdgesGraphReader.scala:169)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader$$anon$5.hasNext(ListOfEdgesGraphReader.scala:171)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at com.twitter.cassovary.util.io.ListOfEdgesGraphReader$OneShardReader$$anon$5.foreach(ListOfEdgesGraphReader.scala:167)
    at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$anonfun$readMetaInfoPerShard$1$$anonfun$2$$anonfun$apply$8.apply(SharedArrayBasedDirectedGraph.scala:91)
    at com.twitter.cassovary.graph.SharedArrayBasedDirectedGraph$SharedArrayBasedDirectedGraphConstructor$$anonfun$readMetaInfoPerShard$1$$anonfun$2$$anonfun$apply$8.apply(SharedArrayBasedDirectedGraph.scala:88)
    at com.twitter.util.Try$.apply(Try.scala:13)
    at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:107)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last cassovary-benchmarks/compile:runMain for the full output.
[error] (cassovary-benchmarks/compile:runMain) Nonzero exit code returned from runner: 1
[error] Total time: 3 s, completed Oct 8, 2016 11:04:03 PM
```

**Comment by lintool** [comment]
This issue has been addressed.
